export const userTypes = {
    SETUSER: "SET_CURRENT_USER",
    SETUSERSESSION:"SET_USER_SESSION",
    SETUSERSIGNINWITHGOOGLESTART:"SET_USER_SIGN_IN_WITH_GOOGLE",
    SETUSERSIGNINWITHEMAILANDPASSWORDSTART:"SET_USER_SIGN_IN_WITH_EMAIL_AND_PASSWORD",
    SETUSERSIGNINSUCCESS:'SIGN_USER_SUCCESS',
    SETUSERSIGNINFAIL:"SIGN_USER_FAIL",
    SETUSERSIGNUPSTART:"SIGN_USER_UP_START",
    SETUSERSIGNUPSUCCESS:"SIGN_USER_UP_SUCCESS",
    SETSIGNOUTSTART:"SIGN_USER_OUT_START",
    SETSIGNOUTSUCCESS:"SIGN_USER_OUT_SUCCESS",
    SETSIGNOUTFAIL:"SIGN_USER_OUT_FAIL"
}